In [5]:
import numpy as np

a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(b)

[[ 0.23967065]
 [-0.26517334]]


In [6]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a+b
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [7]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c)

[[  8.41528086   0.38872837   4.92444373 ...,   3.44503432  -4.03937768
   -6.4427384 ]
 [ -0.3388396   -1.10938579  28.43755673 ...,  20.658735    13.23879821
   -4.99613884]
 [ 16.05341167  -1.69892571  -1.90927942 ...,  11.29414992   5.29377356
    9.66993526]
 ..., 
 [ -0.96664106 -16.57237792 -20.45276504 ...,   4.31788042   5.85207522
    9.63461802]
 [  5.88388565 -11.75406119   8.10258077 ...,  13.82326356   6.26745679
   11.25400479]
 [ -7.80212083 -19.01926635 -17.14381261 ...,  -1.5879059   -5.5775963
    9.4382647 ]]


In [15]:
import numpy as np
# a.shape = (3,4)
# b.shape = (4,1)
a = np.arange(12).reshape(3,4)
b = np.arange(4).reshape(4,1)
c = np.array

print(a)
print(b)
for i in range(3):
  for j in range(4):
    print(a[i][j]+b[j])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]
 [3]]
[0]
[2]
[4]
[6]
[4]
[6]
[8]
[10]
[8]
[10]
[12]
[14]


In [11]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [12]:
c

array([[ 0.59043718,  0.07016649,  0.75308494],
       [-1.25758321,  0.72539702,  0.57391019],
       [-2.35818603,  1.57922467, -1.04984892]])