## The Basics

In [7]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [14]:
a.ndim

2

In [23]:
b = np.array([[[1, 2],[3, 4]],
           [[1, 4],[3, 2]],
           [[2, 4],[4, 3]]])
b

array([[[1, 2],
        [3, 4]],

       [[1, 4],
        [3, 2]],

       [[2, 4],
        [4, 3]]])

In [27]:
type(b)

numpy.ndarray

### Array Creation

In [28]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [29]:
a.dtype

dtype('int64')

In [30]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [32]:
a = np.array([1,2,3,4])

In [33]:
a

array([1, 2, 3, 4])

In [34]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [38]:
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [40]:
np.zeros( [3,4] )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [41]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [43]:
np.empty( (2,3) )

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [44]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [51]:
np.arange( 0, 2, 0.3 )

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [46]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [47]:
x = np.linspace( 0, 2*pi, 100 )

In [48]:
f = np.sin(x)

### Printing Arrays

In [53]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [54]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [59]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [60]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [61]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [63]:
np.set_printoptions(threshold='nan')

### Basic Operations

In [1]:
import numpy as np

a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [2]:
c = a-b
c

array([20, 29, 38, 47])

In [3]:
b**2

array([0, 1, 4, 9])

In [4]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [5]:
a<35

array([ True,  True, False, False], dtype=bool)

In [13]:
A = np.array([[1,1],
             [0,1]])
B = np.array([[2,0],
             [3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [14]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [15]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [16]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [22]:
b += a
b

array([[ 3.33170547,  3.97475169,  3.42617624],
       [ 3.27909683,  3.74405533,  3.73038206]])

In [23]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [25]:
from numpy import pi

a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [26]:
c = a+b

In [27]:
c

array([ 1.        ,  2.57079633,  4.14159265])

In [29]:
c.dtype.name

'float64'

In [30]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [31]:
d.dtype.name

'complex128'

In [35]:
a = np.random.random((2,3))
a

array([[ 0.25408713,  0.86692235,  0.8799579 ],
       [ 0.93966655,  0.18559675,  0.58361296]])

In [36]:
a.sum()

3.7098436280208484

In [37]:
a.min()

0.1855967464503242

In [38]:
a.max()

0.9396665456913702

In [59]:
b = np.arange(12).reshape(3,4)

In [60]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [79]:
b.min(axis=1)

array([0, 4, 8])

In [81]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Universal Functions

In [84]:
B = np.arange(3)
B

array([0, 1, 2])

In [85]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [86]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [88]:
C = np.array([2. ,-1., 4.])

In [89]:
np.add(B,C)

array([ 2.,  0.,  6.])

### Indexing, Slicing and Lterating

In [90]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [91]:
a[2]

8

In [92]:
a[2:5]

array([ 8, 27, 64])

In [93]:
a[:6:2] = -1000

In [94]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [95]:
a[: :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [96]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [101]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [102]:
b[2,3]

23

In [103]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [104]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [105]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [106]:
b[-1]

array([40, 41, 42, 43])

In [108]:
c = np.array([[[ 0, 1, 2],
              [ 10, 12, 13]],
             [[100,101,102],
             [110,112,113]]])
c.shape

(2, 2, 3)

In [109]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [110]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [111]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [114]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Changing the shape of an array

In [115]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 2.,  3.,  5.,  2.],
       [ 4.,  7.,  6.,  8.],
       [ 5.,  4.,  0.,  5.]])

In [116]:
a.ravel()

array([ 2.,  3.,  5.,  2.,  4.,  7.,  6.,  8.,  5.,  4.,  0.,  5.])

In [117]:
a.reshape(6,2)

array([[ 2.,  3.],
       [ 5.,  2.],
       [ 4.,  7.],
       [ 6.,  8.],
       [ 5.,  4.],
       [ 0.,  5.]])

In [118]:
a.T

array([[ 2.,  4.,  5.],
       [ 3.,  7.,  4.],
       [ 5.,  6.,  0.],
       [ 2.,  8.,  5.]])

In [119]:
a.T.shape

(4, 3)

In [120]:
a.shape

(3, 4)

In [121]:
a

array([[ 2.,  3.,  5.,  2.],
       [ 4.,  7.,  6.,  8.],
       [ 5.,  4.,  0.,  5.]])

In [122]:
a.resize((2,6))

In [123]:
a

array([[ 2.,  3.,  5.,  2.,  4.,  7.],
       [ 6.,  8.,  5.,  4.,  0.,  5.]])

In [126]:
a.reshape(3, -1)

array([[ 2.,  3.,  5.,  2.],
       [ 4.,  7.,  6.,  8.],
       [ 5.,  4.,  0.,  5.]])

### Stacking together different arrays

In [127]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 3.,  5.],
       [ 8.,  8.]])

In [129]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 8.,  1.],
       [ 3.,  5.]])

In [130]:
np.vstack((a,b))

array([[ 3.,  5.],
       [ 8.,  8.],
       [ 8.,  1.],
       [ 3.,  5.]])

In [131]:
np.hstack((a,b))

array([[ 3.,  5.,  8.,  1.],
       [ 8.,  8.,  3.,  5.]])

In [132]:
from numpy import newaxis

In [133]:
np.column_stack((a,b))

array([[ 3.,  5.,  8.,  1.],
       [ 8.,  8.,  3.,  5.]])

In [134]:
a = np.array([4.,2.])
b = np.array([2.,8.])

In [136]:
a[:,newaxis]

array([[ 4.],
       [ 2.]])

In [137]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [138]:
np.vstack((a[:,newaxis],b[:,newaxis]))

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

In [141]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

### Splitting one array into several smaller ones

In [143]:
a = np.floor(10*np.random.random((2,12)))
a

array([[ 7.,  8.,  0.,  7.,  7.,  4.,  1.,  4.,  6.,  1.,  8.,  5.],
       [ 8.,  8.,  0.,  1.,  5.,  5.,  7.,  5.,  0.,  3.,  0.,  5.]])

In [144]:
np.hsplit(a,3)

[array([[ 7.,  8.,  0.,  7.],
        [ 8.,  8.,  0.,  1.]]), array([[ 7.,  4.,  1.,  4.],
        [ 5.,  5.,  7.,  5.]]), array([[ 6.,  1.,  8.,  5.],
        [ 0.,  3.,  0.,  5.]])]

In [145]:
np.hsplit(a,(3,4))

[array([[ 7.,  8.,  0.],
        [ 8.,  8.,  0.]]), array([[ 7.],
        [ 1.]]), array([[ 7.,  4.,  1.,  4.,  6.,  1.,  8.,  5.],
        [ 5.,  5.,  7.,  5.,  0.,  3.,  0.,  5.]])]