## The Basics

In [7]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [14]:
a.ndim

2

In [23]:
b = np.array([[[1, 2],[3, 4]],
           [[1, 4],[3, 2]],
           [[2, 4],[4, 3]]])
b

array([[[1, 2],
        [3, 4]],

       [[1, 4],
        [3, 2]],

       [[2, 4],
        [4, 3]]])

In [27]:
type(b)

numpy.ndarray

### Array Creation

In [28]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [29]:
a.dtype

dtype('int64')

In [30]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [32]:
a = np.array([1,2,3,4])

In [33]:
a

array([1, 2, 3, 4])

In [34]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [38]:
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [40]:
np.zeros( [3,4] )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [41]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [43]:
np.empty( (2,3) )

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [44]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [51]:
np.arange( 0, 2, 0.3 )

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [46]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [47]:
x = np.linspace( 0, 2*pi, 100 )

In [48]:
f = np.sin(x)