## The Basics

In [7]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [14]:
a.ndim

2

In [23]:
b = np.array([[[1, 2],[3, 4]],
           [[1, 4],[3, 2]],
           [[2, 4],[4, 3]]])
b

array([[[1, 2],
        [3, 4]],

       [[1, 4],
        [3, 2]],

       [[2, 4],
        [4, 3]]])

In [27]:
type(b)

numpy.ndarray

### Array Creation

In [28]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [29]:
a.dtype

dtype('int64')

In [30]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [32]:
a = np.array([1,2,3,4])

In [33]:
a

array([1, 2, 3, 4])

In [34]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [38]:
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [40]:
np.zeros( [3,4] )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [41]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [43]:
np.empty( (2,3) )

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [44]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [51]:
np.arange( 0, 2, 0.3 )

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [46]:
from numpy import pi
np.linspace( 0, 2, 9 )

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [47]:
x = np.linspace( 0, 2*pi, 100 )

In [48]:
f = np.sin(x)

### Printing Arrays

In [53]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [54]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [59]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [60]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [61]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [63]:
np.set_printoptions(threshold='nan')

### Basic Operations

In [1]:
import numpy as np

a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [2]:
c = a-b
c

array([20, 29, 38, 47])

In [3]:
b**2

array([0, 1, 4, 9])

In [4]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [5]:
a<35

array([ True,  True, False, False], dtype=bool)

In [13]:
A = np.array([[1,1],
             [0,1]])
B = np.array([[2,0],
             [3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [14]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [15]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [16]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [22]:
b += a
b

array([[ 3.33170547,  3.97475169,  3.42617624],
       [ 3.27909683,  3.74405533,  3.73038206]])

In [23]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [25]:
from numpy import pi

a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [26]:
c = a+b

In [27]:
c

array([ 1.        ,  2.57079633,  4.14159265])

In [29]:
c.dtype.name

'float64'

In [30]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [31]:
d.dtype.name

'complex128'

In [35]:
a = np.random.random((2,3))
a

array([[ 0.25408713,  0.86692235,  0.8799579 ],
       [ 0.93966655,  0.18559675,  0.58361296]])

In [36]:
a.sum()

3.7098436280208484

In [37]:
a.min()

0.1855967464503242

In [38]:
a.max()

0.9396665456913702

In [39]:
b = np.arange(12).reshape(3,4)

In [40]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [44]:
b.min(axis=1)

array([0, 4, 8])

In [51]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])